CIS598PROJECT/Models/DrinkShot.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIS598PROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrinkShot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DrinkShot()
        {
            this.IngredientRecipes = new HashSet<IngredientRecipe>();
        }
    
        public string Name { get; set; }
        public string SubmittedBy { get; set; }
        public string Instructions { get; set; }
        public Nullable<int> RatingTotal { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public byte[] Image { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public System.DateTime Date { get; set; }
        public string Type { get; set; }
        public Nullable<bool> Show { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngredientRecipe> IngredientRecipes { get; set; }
    }
}

CIS598PROJECT/Controllers/DrinkShotsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace CIS598PROJECT.Models
{
    public class DrinkShotsController : Controller
    {
        private BTBDatabase_1Entities2 db = new BTBDatabase_1Entities2();

        // GET: DrinkShots
        public ActionResult Index()
        {
            var drinkShots = db.DrinkShots.Include(d => d.User);
            return View(drinkShots.ToList());
        }
        [HttpPost]
        public ActionResult Index(string id)
        {
            var drinkshots = from m in db.DrinkShots
                              select m;
            var ingredients = from m in db.IngrediantRecipes
                              select m;

            if (!String.IsNullOrEmpty(id))
            {
                drinkshots = drinkshots.Where(s => s.Name.Contains(id) ||
                                                s.Type.Contains(id) ||
                                                s.SubmittedBy.Contains(id));
                
            }

            return View(drinkshots);
        }
        // GET: DrinkShots/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DrinkShot drinkShot = db.DrinkShots.Find(id);
            if (drinkShot == null)
            {
                return HttpNotFound();
            }
            return View(drinkShot);
        }

        // GET: DrinkShots/Create
        public ActionResult Create()
        {
            ViewBag.SubmittedBy = new SelectList(db.Users, "User1", "Email");
            var model = new DSCreateModel();
            model.IngredientList = (from m in db.Ingrediants
                                    orderby m.Name
                                    select m).ToList();
            return View(model);
        }

        // POST: DrinkShots/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(DSCreateModel DSCreate)
        //public ActionResult Create([Bind(Include = "Name,SubmittedBy,Instructions,RatingTotal,ViewCount,Image,Cost,Date,Type")] DrinkShot drinkShot)
        {
            HttpPostedFileBase file = Request.Files["ImageData"];
            BTBDatabase_1Entities2 service = new BTBDatabase_1Entities2();
            db = new BTBDatabase_1Entities2();
            DSCreate.Drinkshot.Image = new Controllers.ConversionController().ConvertToBytes(file);
            DSCreate.Drinkshot.Cost = System.Convert.ToDecimal(CalculateCost(DSCreate.SelectedIngredients).ToString("#.##"));
            DSCreate.Drinkshot.RatingTotal = 0;
            DSCreate.Drinkshot.ViewCount = 0;
            
            for (int i = 0; i < DSCreate.SelectedIngredients.Count(); i++)
            {
                
                DSCreate.Recipe = new IngrediantRecipe();
                DSCreate.Recipe.DSName = DSCreate.Drinkshot.Name;
                DSCreate.Recipe.IngrediantName = DSCreate.SelectedIngredients[i];
                DSCreate.Recipe.Ounces = 0;
                DSCreate.Recipe.Id = 1 + i + db.IngrediantRecipes.Count();
                db.IngrediantRecipes.Add(DSCreate.Recipe);
            }
            db.DrinkShots.Add(DSCreate.Drinkshot);
            if (ModelState.IsValid)
            {
                
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            DSCreate.IngredientList = (from m in db.Ingrediants
                                    orderby m.Name
                                    select m).ToList();
            ViewBag.SubmittedBy = new SelectList(db.Users, "User1", "Email", DSCreate.Drinkshot);
            return View(DSCreate);
        }

        // GET: DrinkShots/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DrinkShot drinkShot = db.DrinkShots.Find(id);
            if (drinkShot == null)
            {
                return HttpNotFound();
            }
            ViewBag.SubmittedBy = new SelectList(db.Users, "User1", "Email", drinkShot.SubmittedBy);
            return View(drinkShot);
        }

        // POST: DrinkShots/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Name,SubmittedBy,Instructions,RatingTotal,ViewCount,Image,Cost,Date,Type")] DrinkShot drinkShot)
        {
            if (ModelState.IsValid)
            {
                db.Entry(drinkShot).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.SubmittedBy = new SelectList(db.Users, "User1", "Email", drinkShot.SubmittedBy);
            return View(drinkShot);
        }

        // GET: DrinkShots/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DrinkShot drinkShot = db.DrinkShots.Find(id);
            if (drinkShot == null)
            {
                return HttpNotFound();
            }
            return View(drinkShot);
        }

        // POST: DrinkShots/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            DrinkShot drinkShot = db.DrinkShots.Find(id);
            db.DrinkShots.Remove(drinkShot);
            List<IngrediantRecipe> recipe = db.IngrediantRecipes.Where(m=>m.DSName.Equals(id)).ToList();
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        
        /// <summary>
        /// Calculates the cost for drinks.
        /// </summary>
        /// <param name="Ingredients"></param>
        /// <returns></returns>
        public decimal CalculateCost(string[] Ingredients)
        {
            
            decimal cost = 0;
            for (int i = 0; i < Ingredients.Count(); i++)
            {
                decimal temp = 0;
                var c = db.Ingrediants.Find(Ingredients[i]);
                if (c.CostLiter.HasValue) temp = c.CostLiter.Value;
                temp = decimal.Divide((temp * System.Convert.ToDecimal(1.25)), System.Convert.ToDecimal(33.81 * Ingredients.Count()));
                cost += temp;
            }
            return cost;
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult RetrieveImage(string id)
        {
            byte[] cover = GetImageFromDataBase(id);
            if (cover != null)
            {
                return File(cover, "image/jpg");
            }
            else
            {
                return null;
            }
        }

        public byte[] GetImageFromDataBase(string name)
        {
            byte[] cover = null;
            var q = from temp in db.DrinkShots where temp.Name.Equals(name) select temp.Image;
            try
            {
                cover = q.First();
            }
            catch
            {

            }
            return cover;
        }




    }
}

CIS598PROJECT/Views/DrinkShots/Create.cshtml
@model CIS598PROJECT.Models.DSCreateModel
@using Microsoft.AspNet.Identity

@{
    ViewBag.Title = "Create";
}


@using (Html.BeginForm("Create", "DrinkShots", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h2>Create: Mix Drink or Shot</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Drinkshot.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Drinkshot.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Drinkshot.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Drinkshot.SubmittedBy, "SubmittedBy", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @if (User.Identity.GetUserName() != "")
                {
                    @Html.TextBoxFor(model => model.Drinkshot.SubmittedBy, htmlAttributes: new { @Value = User.Identity.GetUserName(), @readonly = "readonly", @class = "form-control" })
                }
                else
                {
                    @Html.TextBoxFor(model => model.Drinkshot.SubmittedBy, htmlAttributes: new { @Value = "Anonymous", @readonly = "readonly", @class = "form-control" })
                }
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Drinkshot.Instructions, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Drinkshot.Instructions, new { htmlAttributes = new { @class = "form-control textarea" } })
                @Html.ValidationMessageFor(model => model.Drinkshot.Instructions, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Drinkshot.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ImageData" id="ImageData" onchange="fileCheck(this);" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Drinkshot.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Drinkshot.Date, new { htmlAttributes = new { @Value = DateTime.Now.ToString("yyyy-MM-dd"), @readonly = "readonly", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Drinkshot.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Drinkshot.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Drinkshot.Type, new SelectList(new[] { "Drink","Shot" }), new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Drinkshot.Type, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Ingredients", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBoxFor(model => model.SelectedIngredients, new MultiSelectList(Model.IngredientList.Select(m => m.Name), "Name") ,new { @multiple = "multiple", @class = "styled-select form-control" })
                <br /> 
                Hold Ctrl then click for multiple selections or @Html.ActionLink("Create", "Create", "Ingredients") a new ingredient if yours is not shown.
                @Html.ValidationMessageFor(model => model.Recipe, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index") | @Html.ActionLink("Alcohol List", "Index", "Ingredients")
</div>

@*$('option').mousedown(function(e) {
    e.preventDefault();
    $(this).prop('selected', !$(this).prop('selected'));
    return false;
});*@

CIS598PROJECT/Views/DrinkShots/Delete.cshtml
@model CIS598PROJECT.Models.DrinkShot

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DrinkShot</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Instructions)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Instructions)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RatingTotal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RatingTotal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ViewCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ViewCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Email)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CIS598PROJECT/Views/DrinkShots/Details.cshtml
@model CIS598PROJECT.Models.DrinkShot

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>DrinkShot</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Instructions)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Instructions)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RatingTotal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RatingTotal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ViewCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ViewCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            <img src="/DrinkShots/RetrieveImage/@Model.Name" i alt="No Image Uploaded" height=300 width=300 />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Email)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Name }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CIS598PROJECT/Views/DrinkShots/Edit.cshtml
@model CIS598PROJECT.Models.DrinkShot

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DrinkShot</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Name)

        <div class="form-group">
            @Html.LabelFor(model => model.SubmittedBy, "SubmittedBy", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SubmittedBy", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SubmittedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Instructions, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Instructions, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Instructions, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RatingTotal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RatingTotal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RatingTotal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ViewCount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ViewCount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ViewCount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CIS598PROJECT/Views/DrinkShots/Index.cshtml
@model IEnumerable<CIS598PROJECT.Models.DrinkShot>
@using Microsoft.AspNet.Identity

@{
    ViewBag.Title = "Mix List";
}

<div class="padding-top-table">
    <div class="create-new-tab">@Html.ActionLink("Mix List", "Index")</div>

    <div class="create-new-tab">
        @Html.ActionLink("Create New", "Create")
    </div>
    <div class="search-tab">
        <div class="float-left">
            Search Drinks/Shots:
        </div>
        @using (Html.BeginForm("Index", "DrinkShots", FormMethod.Post))
        {
        <div class="float-left">
            
                @Html.TextBox("id", "", new { htmlAttributes = new { @class = "form-control" } })
            
        </div>
        <div class="float-left">
            <input type="submit" value="Search" class="btn-warning search-btn" />
        </div>
            }
    </div>
</div>
<table class="zui-table zui-table-rounded">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Instructions)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cost)
            </th>
            <th>
                Submission @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                Submitted By
            </th>
            <th>
                Ingredients
            </th>
            <th></th>

        </tr>
    </thead>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(model => item.Name, new { @class="ingredient-index"})
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Instructions, new { @class = "ingredient-index" })
            </td>
            <td>
                <img class="thumbnail-index" src="/DrinkShots/RetrieveImage/@item.Name" i alt="No Image Uploaded" />
            </td>
            <td>
                $@Html.DisplayFor(modelItem => item.Cost, new { @class = "ingredient-index" })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date, new { @class = "ingredient-index" })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type, new { @class = "ingredient-index" })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.User1, new { @class = "ingredient-index" })
            </td>
            <td>
                @foreach (var d in item.IngrediantRecipes.Where(d => d.DSName == item.Name))
                {
                    <div>
                        <a href="@Href("/Ingredients/Details/" + @d.IngrediantName)" class="ingredient-index">@d.IngrediantName</a>
                    </div>
                }
            </td>
            <td>
                <div class="btn-block">
                    @Html.ActionLink("Edit", "Edit", new { id = item.Name }, new { @class = "ingredient-index" })
                </div>
                <div class="btn-block">
                    @Html.ActionLink("Details", "Details", new { id = item.Name }, new { @class = "ingredient-index" })
                </div>
                <div class="btn-block">
                    @Html.ActionLink("Delete", "Delete", new { id = item.Name }, new { @class = "ingredient-index" })
                </div>
            </td>
        </tr>
    }

</table>