CIS598PROJECT/Models/Ingredient.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIS598PROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ingredient()
        {
            this.IngredientRecipes = new HashSet<IngredientRecipe>();
        }
    
        public string Name { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
        public string SubmittedBy { get; set; }
        public Nullable<decimal> CostLiter { get; set; }
        public System.DateTime Date { get; set; }
        public string Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngredientRecipe> IngredientRecipes { get; set; }
        public virtual User User { get; set; }
    }
}

CIS598PROJECT/Controllers/IngredientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using CIS598PROJECT.Models;

namespace CIS598PROJECT.Models
{
    public class IngredientsController : Controller
    {
        private BTBDatabase_1Entities2 db = new BTBDatabase_1Entities2();
        //private string identity = 
        // GET: Ingredients
        public ActionResult Index()
        {
            var ingrediants = db.Ingrediants.Include(i => i.User);
            return View(ingrediants.ToList());
        }

        public byte[] GetImageFromDataBase(string name)
        {
            byte[] cover = null;
            var q = from temp in db.Ingrediants where temp.Name.Equals(name) select temp.Image;
            try
            {
                cover = q.First();
            }
            catch
            {

            }
            return cover;
        }
        /// <summary>
        /// Search for Ingredients index
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Index(string id)
        {
            var ingredients = from m in db.Ingrediants
                              select m;

            if (!String.IsNullOrEmpty(id))
            {
                ingredients = ingredients.Where(s => s.Name.Contains(id) ||
                                                s.Type.Contains(id) ||
                                                s.SubmittedBy.Contains(id) ||
                                                s.Description.Contains(id));

            }

            return View(ingredients);
        }


        // GET: Ingredients/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ingrediant ingrediant = db.Ingrediants.Find(id);
            if (ingrediant == null)
            {
                return HttpNotFound();
            }
            return View(ingrediant);
        }

        // GET: Ingredients/Create

        public ActionResult Create()
        {
            return View();
        }

        // POST: Ingredients/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Route("Create")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name,Description,Image,SubmittedBy,CostLiter,Date,Type")] Ingrediant ingrediant)
        {
            ViewBag.SubmittedBy = new SelectList(db.Users, "User1", "Email");
            HttpPostedFileBase file = Request.Files["ImageData"];
            BTBDatabase_1Entities2 service = new BTBDatabase_1Entities2();
            db = new BTBDatabase_1Entities2();
            ingrediant.Image = new Controllers.ConversionController().ConvertToBytes(file);
            
            if (ModelState.IsValid)
            {
                db.Ingrediants.Add(ingrediant);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.SubmittedBy = new SelectList(db.Users, "User1", "Email", ingrediant.SubmittedBy);
            return View(ingrediant);
        }

        // GET: Ingredients/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ingrediant ingrediant = db.Ingrediants.Find(id);
            if (ingrediant == null)
            {
                return HttpNotFound();
            }
            ViewBag.SubmittedBy = new SelectList(db.Users, "User1", "Email", ingrediant.SubmittedBy);
            return View(ingrediant);
        }

        // POST: Ingredients/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Name,Description,Image,SubmittedBy,CostLiter,Date,Type")] Ingrediant ingrediant)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ingrediant).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.SubmittedBy = new SelectList(db.Users, "User1", "Email", ingrediant.SubmittedBy);
            return View(ingrediant);
        }

        // GET: Ingredients/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ingrediant ingrediant = db.Ingrediants.Find(id);
            if (ingrediant == null)
            {
                return HttpNotFound();
            }
            return View(ingrediant);
        }

        // POST: Ingredients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Ingrediant ingrediant = db.Ingrediants.Find(id);
            db.Ingrediants.Remove(ingrediant);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //Retrieve an image from a databases
        [HttpGet]
        public ActionResult RetrieveImage(string id)
        {
            byte[] cover = GetImageFromDataBase(id);
            if (cover != null)
            {
                return File(cover, "image/jpg");
            }
            else
            {
                return null;
            }
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CIS598PROJECT/Views/Ingredients/Create.cshtml
@model CIS598PROJECT.Models.Ingrediant
@using Microsoft.AspNet.Identity

@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm("Create", "Ingredients", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h2>Create: Alcohol</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control text-area" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ImageData" id="ImageData" onchange="fileCheck(this);" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SubmittedBy, "SubmittedBy", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @if(User.Identity.GetUserName()!="")
                {
                    @Html.TextBoxFor(model => model.SubmittedBy, htmlAttributes: new { @Value = User.Identity.GetUserName(), @readonly="readonly", @class = "form-control"})
                }
                else
                {
                    @Html.TextBoxFor(model => model.SubmittedBy, htmlAttributes: new { @Value = "Anonymous", @readonly = "readonly", @class = "form-control" })
                }
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CostLiter, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CostLiter, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CostLiter, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @Value = DateTime.Now.ToString("yyyy-MM-dd"), @readonly = "readonly", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.ListBoxFor(model => model.Type, new SelectList(new[] { "Liqour", "Mixer", "Beer", "Wine", "liqueur", "Champagne" }), new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index") | @Html.ActionLink("Mix List", "Index", "DrinkShots")
</div>

CIS598PROJECT/Views/Ingredients/Delete.cshtml
@model CIS598PROJECT.Models.Ingredient

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Ingredient</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CostLiter)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CostLiter)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Email)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CIS598PROJECT/Views/Ingredients/Details.cshtml
@model CIS598PROJECT.Models.Ingredient

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Ingredient</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            <img src="/Ingredients/RetrieveImage/@Model.Name" i alt="No Image Uploaded" height=100 width=100 />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CostLiter)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CostLiter)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayName("Submitted By")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.User1)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Name }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CIS598PROJECT/Views/Ingredients/Edit.cshtml
@model CIS598PROJECT.Models.Ingredient
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Ingredients", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Ingredient</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Name)

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control text-area" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ImageData" id="ImageData" onchange="fileCheck(this);" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SubmittedBy, "SubmittedBy", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @if (User.Identity.GetUserName() != "")
                {
                    @Html.TextBoxFor(model => model.SubmittedBy, htmlAttributes: new { @Value = User.Identity.GetUserName(), @readonly = "readonly", @class = "form-control" })
                }
                else
                {
                    @Html.TextBoxFor(model => model.SubmittedBy, htmlAttributes: new { @Value = "Anonymous", @readonly = "readonly", @class = "form-control" })
                }
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CostLiter, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CostLiter, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CostLiter, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @Value = DateTime.UtcNow, @readonly = "readonly", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.DropDownListFor(model => model.Type, new SelectList(new[] { "Liqour", "Mixer", "Beer", "Wine", "Liqueur", "Champagne" }), new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CIS598PROJECT/Views/Ingredients/Index.cshtml
@model IEnumerable<CIS598PROJECT.Models.Ingrediant>

@{
    ViewBag.Title = "Ingredients List";
}
<div class="padding-top-table">
    <div class="create-new-tab">@Html.ActionLink("Alcohol List", "Index", "Ingredients")</div>

    <div class="create-new-tab">
        @Html.ActionLink("Create New", "Create")
    </div>
    <div class="search-tab">
        <div class="float-left">
            Search Drinks/Shots:
        </div>
        @using (Html.BeginForm("Index", "Ingredients", FormMethod.Post))
        {
            <div class="float-left">

                @Html.TextBox("id", "", new { htmlAttributes = new { @class = "form-control" } })

            </div>
            <div class="float-left">
                <input type="submit" value="Search" class="btn-warning search-btn" />
            </div>
        }
    </div>

</div>
<table class="zui-table zui-table-rounded">
    <tr>
        <thead>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CostLiter)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Type)
        </th>
        <th>
            @Html.DisplayName("Submitted By")
        </th>
        <th></th>
    </thead>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>

            <td>
                @*<img src="@Url.Action("RetrieveImage", "Ingrediants", new { name = item.Name })" alt="No Image Uploaded" height=100 width=200 />*@
                <img class="thumbnail-index" src="/Ingredients/RetrieveImage/@item.Name" i alt="No Image Uploaded" />
            </td>
            <td>
                $@Html.DisplayFor(modelItem => item.CostLiter)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.User1)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Name }) |
                @Html.ActionLink("Details", "Details", new { id = item.Name }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Name }) |
            </td>
        </tr>
        
    }

</table>

CIS598PROJECT/Views/Ingredients/_AlcoholTable.cshtml
@model IEnumerable<CIS598PROJECT.Models.Ingredient>

<table class="zui-table zui-table-rounded">
    <tr>
    <thead>
    <th>
        @Html.DisplayNameFor(model => model.Name)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.Description)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.Image)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.CostLiter)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.Date)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.Type)
    </th>
    <th>
        @Html.DisplayName("Submitted By")
    </th>
    <th></th>
    </thead>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>

            <td>
                @*<img src="@Url.Action("RetrieveImage", "Ingredients", new { name = item.Name })" alt="No Image Uploaded" height=100 width=200 />*@
                <img class="thumbnail-index" src="/Ingredients/RetrieveImage/@item.Name" i alt="No Image Uploaded" />
            </td>
            <td>
                $@Html.DisplayFor(modelItem => item.CostLiter)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.User1)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Name }) |
                @Html.ActionLink("Details", "Details", new { id = item.Name }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Name }) |
            </td>
        </tr>

    }

</table>

CIS598PROJECT/Views/Ingredients/_IdentityPartial.cshtml
@using Microsoft.AspNet.Identity
@if (Request.IsAuthenticated)
{
    @Html.AntiForgeryToken()
    @User.Identity.GetUserName()
}